apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: retool-postgres-{{ .Values.workspace.terraformVariables.vv_rds_env_identifier }}
spec:
  organization: {{ .Values.tfc.organization }}
  token:
    secretKeyRef:
      name: hcp-terraform-operator-{{ .Values.workspace.terraformVariables.vv_rds_env_identifier }}-tfc-operator
      key: token
  destroyOnDeletion: true
  module:
    source:  "app.terraform.io/testorgvv/vv-rds/aws"
    version: "0.0.22"
  variables:
    - name: vv_rds_env_identifier
    - name: vv_rds_vpc_id
    - name: vv_rds_subnet_id_0
    - name: vv_rds_subnet_id_1
  workspace:
    name: retool-{{ .Values.workspace.terraformVariables.vv_rds_env_identifier }}
